### ISSUE TITLE
Production start rate stocked obs time series converge to zero

### ISSUE THREAD

**Issue by hyunjimoon** [Data4DM/stanify#11]
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/30194633/199134629-2d682daa-2b53-4e9e-8019-a073f8fbce8b.png">

Parameter retrieval seems ok
<img width="899" alt="image" src="https://user-images.githubusercontent.com/30194633/199134896-11d7ce8f-d49d-403c-b211-cfb9bb98d19d.png">

**Comment by hyunjimoon** [comment]
Sometimes, it increase.
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/30194633/201368834-e4ffd046-da15-4b2c-b6d6-6920b8555d40.png">

 With this state pattern and estimating six parameters, parameters seem to be very bimodal. Stan gave the following msg:
```
	Chain 1 had 50 iterations at max treedepth (100.0%)
	Chain 2 had 50 iterations at max treedepth (100.0%)
```
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/30194633/201369254-546daf4c-5f9d-47b1-a0d8-aa57203240ac.png">

The above is in contrast with two parameter estimation:
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/30194633/201369452-43deda9d-c845-4a0f-b7d8-4eb6d30582f9.png">

**Comment by tomfid** [comment]
Can you plot a few individual trajectories from the model? Diagnosing from aggregates is difficult.

**Comment by tomfid** [comment]
This seems like it has to be an ODE formulation error. In the long run, production rate >> production start rate implies that WIP is going dramatically negative.

**Comment by tomfid** [comment]
If the Vensim version is ground truth, the inventory adj time is OK but the minimum order processing time is off (I think it's 2 in the Vensim model?).

Inventory and WIP adjustment times would make a better pair for a 2-parameter experiment. Order processing time is physics, and probably not very uncertain, nor very important to the behavior.

**Comment by hyunjimoon** [comment]
This disappear (perhaps we were seeing only the very first era) so closing. But I still am curious why the production start rate dipped at first. Might this be relevant to mis-assigned initial value of stock variables? 
![image](https://user-images.githubusercontent.com/30194633/206460264-8a2ee2c9-8880-4543-9e7b-3aa7a040f161.png)
