### ISSUE TITLE
Documentation and refactoring for initialization

### ISSUE THREAD

**Issue by hyunjimoon** [Data4DM/stanify#3]
I don't know a easy way to combine this repository with the other in BayesSD, so may I ask for some advice on the best way to merge stanify repo with the following commit   https://github.com/Data4DM/BayesSD/commit/b128c3e311f7b228d5371a2d7b55209a333cfbef ? @Dashadower?

Documentation on what different `structure` means and different `parameter` names should be clearly defined.
- callstructure: auxiliary
- reference structure: 
- ignored variables: variables defined as data and all stock 
- exposed parameter: ode function's input
- stan_variable is larger set than vensim parameter

**Comment by hyunjimoon** [comment]
> return super().walk(ast_node)
super복귀 불가, 재귀의 문제점, 방문자 패턴

**Comment by hyunjimoon** [comment]
From this commit 93b513250e0c39d3120c6b478c82de990f8a318a
[this](https://github.com/Data4DM/stanify/blob/main/stan_files/mng_inven_init_test/mng_inven_init_test_functions.stan#L2502) line of stan file shows `adjustment_for_wip = desired_wip - work_in_process_inventory / wip_adjustment_time;` which should be `(desired_wip - work_in_process_inventory)/ wip_adjustment_time;`

Also, stock variables initialization were problematic from previous debuggings. I think the order for declaration is the cause.

**Comment by Dashadower** [comment]
Since I don't have write access to this repo, I made a pull request #10
