### ISSUE TITLE
multiple subscript

### ISSUE THREAD

**Issue by hyunjimoon** [Data4DM/stanify#40]
@Dashadower could you document why you decide using array for multiple subscript?

**Comment by Dashadower** [comment]
Stan matrices are constrained to have 2 dimensions, which is fine when you have just 2 subscripts; you either use a vector for a single subscript and a matrix for 2.

If you want to support 3 or more subscripts, you need a multidimensional data structure that allows 3+ dimensions. Arrays are the only data structure that allows this behavior.

**Comment by hyunjimoon** [comment]
@Dashadower could you close this with a brief summary (name of a function + where it's implemented) when it's complete?

**Comment by Dashadower** [comment]
https://github.com/Data4DM/stanify/blob/4f6fd158de4dcf0da5eb7805053f580f69ceadb4/stanify/builders/stan_model_context.py#L25

This attribute holds the subscript to array-indices mapping. That way the builders know which index of an array corresponds to which subscript.

The builders use that information coupled with defined subscripts to create the array variables and access them. For example in declaring parameters:
https://github.com/Data4DM/stanify/blob/4f6fd158de4dcf0da5eb7805053f580f69ceadb4/stanify/builders/stan_block_codegen.py#L247

You can see that it figures out the stan variable type depending on it has subscripts or not.
